apiVersion: v1
kind: Service
metadata:
  name: planet
spec:
  selector:
    app: planet
    tier: backend
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: planet-deployment
spec:
  replicas: 1
  strategy:
   type: RollingUpdate
   rollingUpdate:
     maxUnavailable: 0
     maxSurge: 1
  selector: 
    matchLabels:
      app: planet
      tier: backend
  template:
    metadata:
      labels:
        app: planet
        tier: backend
    spec:
      containers:
        - name: planet
          image: adenijiazeez/planet
          envFrom:
            - secretRef:
                name: planet-secret
            - configMapRef:
                name: planet-config
          resources:
            requests:
              cpu: 200m
              memory: "512Mi"